Adding AOAI policies to the GenAI Workload
Azure/apim-landing-zone-accelerator pull request #119
Opened 2024-05-23 10:46 UTC by prasann

Adding 2 scenarios based on the new set of AOAI policies, along with the infra setup and docs.

-  Moved the existing rate limiting policy as a workaround and kept the new ones as the default
- Added metric tracking via appinsights and made it as a default.

2024-05-23 13:45 UTC, aarthiem approved these changes
Thanks Prasanna!

2024-05-23 16:54 UTC, seenu433 requested changes

2024-05-23 16:54 UTC, seenu433 commented on scenarios/workload-genai/bicep/apim-policies/apiManagement.bicep
Need to add the diagnostics at the api level

resource apiMonitoring 'Microsoft.ApiManagement/service/apis/diagnostics@2020-06-01-preview' = {
  name: 'applicationinsights'
  parent: azureOpenAIApi
  properties: {
      alwaysLog: 'allErrors'
      loggerId: appInsightsLoggerId
      metrics: true
      logClientIp: true
      httpCorrelationProtocol: 'W3C'
      verbosity: 'information'
      operationNameFormat: 'Url'
  }
}

2024-05-23 16:54 UTC, seenu433 commented on scenarios/workload-genai/policies/fragments/rate-limiting/adaptive-rate-limiting.xml
Not sure of the behavior when multiple policy blocks for rate limiting are applied. also the remainingtokens variable is expected to hold the tokens left for that subscriber alone.

2024-05-23 16:54 UTC, seenu433 commented on scenarios/scripts/deploy-apim-baseline.sh
This location constraint will impact all deployments scenarios. Probably we need to add a description that it is temporary and used for the genai dependencies

2024-05-23 16:54 UTC, seenu433 commented on scenarios/.env
we need to ignore changes to this file. the RANDOM_IDENTIFIER will be autogenerated for each deployment session

2024-05-23 17:26 UTC, prasann commented on scenarios/workload-genai/bicep/apim-policies/apiManagement.bicep
I was thinking of this approach, in this case, we need to pass on the appInsights  value here. but looks like this wasn't needed. the service level diagnostic setting was inherited and worked fine.

2024-05-28 16:15 UTC, seenu433 approved these changes

2024-05-28 16:15 UTC, merged