Feat(Terraform): Baseline and Genai Scenarios
Azure/apim-landing-zone-accelerator pull request #133
Opened 2024-08-09 06:02 UTC by nidhirw

To be updated.

Includes:
- Devcontainer
- Baseline scenario terraform 
- GenAI scenario terraform
- Terraform deployment guide

To discuss:
- Keyvault has public endpoint enabled. Should we change it based on bicep?
- The repository currently uses user-assigned managed identity but the guidelines in the repository suggest to use system-assigned.

2024-08-26 15:55 UTC, seenu433 approved these changes
The changes are good. Functions scenario is pending.

2024-09-08 17:19 UTC, prasann requested changes
apart from these mentioned improvements, i faced couple of intermittent issues while running these scripts.

Issue1:
Post setting up the apim-baseline the script failed here. I see the token got expired, and the difference is about 7 mins. I'm not sure, whether i delayed somewhere or not. But in the next run, it went through.

```
Error: creating User Assigned Identity (Subscription: "xxx"
│ Resource Group Name: "rg-networking-lz00-dev-eastus-nuly"
│ Name: "identity-appgw-lz00-dev-eastus-nuly"): unexpected status 401 (401 Unauthorized) with error: ExpiredAuthenticationToken: The access token expiry UTC time '9/6/2024 9:07:31 AM' is earlier than current UTC time '9/6/2024 9:14:54 AM'.
│
│   with module.gateway.azurerm_user_assigned_identity.user_assigned_identity,
│   on modules/gateway/gateway.tf line 16, in resource "azurerm_user_assigned_identity" "user_assigned_identity":
│   16: resource "azurerm_user_assigned_identity" "user_assigned_identity" {
│
│ creating User Assigned Identity (Subscription: "xxx"
│ Resource Group Name: "rg-networking-lz00-dev-eastus-nuly"
│ Name: "identity-appgw-lz00-dev-eastus-nuly"): unexpected status 401 (401 Unauthorized) with error: ExpiredAuthenticationToken: The access token expiry UTC time '9/6/2024 9:07:31 AM' is earlier than current UTC time '9/6/2024 9:14:54 AM'.
```

Issue 2:

While running `deploy-workload-genai.sh` I got an error once, 

```
Error: creating Policy Fragment (Subscription: "xxx"
│ Resource Group Name: "rg-apim-tlz01-dev-australiaeast-boi"
│ Service Name: "apim-tlz01-dev-australiaeast-boi"
│ Policy Fragment Name: "simple-priority-weighted"): polling after CreateOrUpdate: executing request: unexpected status 404 (404 Not Found) with error: ResourceNotFound: PolicyFragment not found.
│
│   with module.apiManagement.azurerm_api_management_policy_fragment.simpleRoundRobinPolicyFragment,
│   on modules/apim_policies/apimanagement.tf line 88, in resource "azurerm_api_management_policy_fragment" "simpleRoundRobinPolicyFragment":
│   88: resource "azurerm_api_management_policy_fragment" "simpleRoundRobinPolicyFragment" {
```

I was able to locate this file in the mentioned path, and in the second run it did pass.

Just dropping a note on these 2 errors, in case if you have also faced these in the past try to figure a way out or add some workarounds to the troubleshooting guide.

Both the above mentioned issues didn't show up in the subsequent runs. So can't really pin point the issue.

2024-09-08 17:19 UTC, prasann commented on scenarios/apim-baseline/terraform/README.md
> +         --storage-account my-storage-account \
please adjust the storage name without hyphens. helps to do a copy paste.

2024-09-08 17:19 UTC, prasann commented on scenarios/apim-baseline/terraform/README.md
> +
I believe, one of the prerequisites is to have a terraform setup in the local machine.

2024-09-08 17:19 UTC, prasann commented on scenarios/apim-baseline/terraform/README.md
> +   Run the following command to deploy the APIM baseline
add a note to inform users that they will encounter prompts during the script execution and need to respond with `y` to proceed.

2024-09-08 17:19 UTC, prasann commented on scenarios/workload-genai/terraform/README.md
> +Test the hello api using hte generated command from the output
```suggestion
Test the hello api using the generated command from the output
```

2024-09-13 13:50 UTC, aarthiem approved these changes
Thanks @jsburckhardt for the Terraform updates!!

2024-09-13 13:50 UTC, merged